title: FFunFForever
description: Forever Bold • Forever Fun
url: ""  # set to your site URL if you have a custom domain
baseurl: ""  # e.g. /FFunFForever-Site-Jekyll
permalink: /posts/:title/
timezone: Europe/London
markdown: kramdown
theme: null
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
